// Public-integrity facts and publication rules for UK politics and law enforcement.
//
// This file contains institutions, offices, source maps and methods. It is not
// a people dossier. A source-reported donation, meeting, contract, company
// role or land title remains its own fact unless a competent official finding
// explicitly establishes a further relationship.

export type IntegritySource = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  kind: "legislation" | "official-api" | "official-data" | "official-guidance" | "official-register";
  jurisdictions: string[];
  reuse: "open" | "review-required" | "separate-licence" | "link-only";
  personalData: boolean;
  supports: string;
};

export const integritySources: IntegritySource[] = [
  {
    id: "commons-interests-api",
    title: "House of Commons Register of Members' Financial Interests API",
    publisher: "UK Parliament",
    url: "https://interests-api.parliament.uk/index.html",
    kind: "official-api",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Structured current Commons interests, categories, registers and declaration dates.",
  },
  {
    id: "ministerial-benefits",
    title: "Register of Ministers' Gifts and Hospitality",
    publisher: "Cabinet Office",
    url: "https://www.gov.uk/government/collections/register-of-ministers-gifts-and-hospitality",
    kind: "official-data",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Monthly department CSV records of ministerial gifts and hospitality from January 2025.",
  },
  {
    id: "appg-register",
    title: "Register of All-Party Parliamentary Groups",
    publisher: "UK Parliament",
    url: "https://www.parliament.uk/mps-lords-and-offices/standards-and-financial-interests/parliamentary-commissioner-for-standards/registers-of-interests/register-of-all-party-party-parliamentary-groups/",
    kind: "official-register",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "APPG purpose, Parliamentary officers, secretariat and reported external benefits.",
  },
  {
    id: "electoral-commission-pfo",
    title: "Political Finance Online",
    publisher: "Electoral Commission",
    url: "https://search.electoralcommission.org.uk/",
    kind: "official-register",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Official political donations, loans, spending and regulated-entity records; API republication remains closed pending written terms.",
  },
  {
    id: "ipsa-publication",
    title: "How MPs' staffing and business-cost funding is published",
    publisher: "Independent Parliamentary Standards Authority",
    url: "https://www.ipsaonline.org.uk/guidance/how-your-funding-is-published",
    kind: "official-guidance",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Official business-cost publication and bulk-download boundaries; staff identity and security-sensitive fields are excluded.",
  },
  {
    id: "charity-commission-api",
    title: "Charity Commission API documentation",
    publisher: "Charity Commission for England and Wales",
    url: "https://register-of-charities.charitycommission.gov.uk/en/documentation-on-the-api",
    kind: "official-api",
    jurisdictions: ["England", "Wales"],
    reuse: "review-required",
    personalData: true,
    supports: "Identifier-based charity identity, classifications, organisation finances and return dates.",
  },
  {
    id: "government-transparency-publications",
    title: "How to publish central government transparency data",
    publisher: "Cabinet Office",
    url: "https://www.gov.uk/government/collections/how-to-publish-central-government-transparency-data",
    kind: "official-guidance",
    jurisdictions: ["United Kingdom"],
    reuse: "open",
    personalData: false,
    supports: "Source families for ministerial meetings, travel, hospitality, spending and workforce publications.",
  },
  {
    id: "consultant-lobbyists-register",
    title: "Register of Consultant Lobbyists",
    publisher: "Office of the Registrar of Consultant Lobbyists",
    url: "https://registrarofconsultantlobbyists.org.uk/",
    kind: "official-register",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Consultant-lobbyist registrants, organisation clients and quarterly returns.",
  },
  {
    id: "contracts-finder-api",
    title: "Contracts Finder OCDS API",
    publisher: "Cabinet Office",
    url: "https://www.contractsfinder.service.gov.uk/apidocumentation/home",
    kind: "official-api",
    jurisdictions: ["England", "United Kingdom contracting authorities using the service"],
    reuse: "open",
    personalData: true,
    supports: "Published procurement notices and awards in Open Contracting Data Standard form.",
  },
  {
    id: "find-a-tender-api",
    title: "Find a Tender OCDS API documentation",
    publisher: "Cabinet Office",
    url: "https://www.find-tender.service.gov.uk/Developer/Documentation",
    kind: "official-api",
    jurisdictions: ["United Kingdom"],
    reuse: "open",
    personalData: true,
    supports: "UK procurement notices, organisations, identifiers, awards and contracts.",
  },
  {
    id: "companies-house-api",
    title: "Companies House Public Data API",
    publisher: "Companies House",
    url: "https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/reference",
    kind: "official-api",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: true,
    supports: "Identifier-based company identity and filing metadata; person records need a separate decision.",
  },
  {
    id: "government-grants-register",
    title: "Government grants data and statistics",
    publisher: "Cabinet Office",
    url: "https://www.gov.uk/government/collections/government-grants-data-and-statistics",
    kind: "official-data",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: false,
    supports: "Government grant schemes and award data published through the Government Grants Register.",
  },
  {
    id: "uk-subsidy-database",
    title: "View subsidies awarded by UK government",
    publisher: "Department for Business and Trade",
    url: "https://www.gov.uk/guidance/view-subsidies-awarded-by-uk-government",
    kind: "official-register",
    jurisdictions: ["United Kingdom"],
    reuse: "review-required",
    personalData: false,
    supports: "Published subsidy schemes and awards, authorities, beneficiaries, values or bands and legal basis.",
  },
  {
    id: "hmlr-public-data",
    title: "HM Land Registry public data",
    publisher: "HM Land Registry",
    url: "https://www.gov.uk/government/publications/hm-land-registry-data/public-data",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "separate-licence",
    personalData: true,
    supports: "Dataset-by-dataset access, licence and rights boundaries for land and property data.",
  },
  {
    id: "hmlr-corporate-ownership",
    title: "UK companies that own property in England and Wales",
    publisher: "HM Land Registry",
    url: "https://www.gov.uk/guidance/hm-land-registry-uk-companies-that-own-property-in-england-and-wales",
    kind: "official-data",
    jurisdictions: ["England", "Wales"],
    reuse: "separate-licence",
    personalData: false,
    supports: "Separately licensed corporate ownership records; it is not a natural-person property search.",
  },
  {
    id: "police-api",
    title: "data.police.uk API",
    publisher: "Home Office",
    url: "https://data.police.uk/docs/",
    kind: "official-api",
    jurisdictions: ["England", "Wales", "Northern Ireland where supplied"],
    reuse: "open",
    personalData: true,
    supports: "Force institutions and force-published senior officers; operational and lower-rank data are excluded here.",
  },
  {
    id: "police-workforce-ew",
    title: "Police workforce, England and Wales: open data tables",
    publisher: "Home Office",
    url: "https://www.gov.uk/government/statistics/police-workforce-open-data-tables",
    kind: "official-data",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "Official aggregate workforce, rank, sex and ethnicity statistics with disclosure controls.",
  },
  {
    id: "police-pay-ew-2026",
    title: "Home Office evidence to the Police Remuneration Review Body: 2026 to 2027",
    publisher: "Home Office",
    url: "https://www.gov.uk/government/publications/home-office-evidence-to-the-police-remuneration-review-body-2026-to-2027/home-office-evidence-to-the-police-remuneration-review-body-2026-to-2027-accessible",
    kind: "official-data",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "Pay scales, allowances, pensions and workforce remuneration evidence.",
  },
  {
    id: "police-grants-ew-2026",
    title: "Police grants in England and Wales: 2026 to 2027",
    publisher: "Home Office",
    url: "https://www.gov.uk/government/publications/police-grants-in-england-and-wales-2026-to-2027",
    kind: "official-data",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "Central police grant allocations, which remain distinct from precepts, reserves and actual expenditure.",
  },
  {
    id: "chief-constable-profile",
    title: "Chief constable professional profile",
    publisher: "College of Policing",
    url: "https://www.college.police.uk/career-learning/support-for-career-development/policing-professional-profiles/core-rank-profiles/chief-constable",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "link-only",
    personalData: false,
    supports: "Independent operational command and generic chief-constable accountabilities.",
  },
  {
    id: "pcc-panel-guidance",
    title: "Police, fire and crime panels: guidance",
    publisher: "Home Office",
    url: "https://www.gov.uk/government/publications/police-and-crime-panels/police-fire-and-crime-panels-guidance",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "PCC strategy, budget and chief-officer appointment accountability, plus panel scrutiny.",
  },
  {
    id: "iopc-role",
    title: "Independent Office for Police Conduct framework document",
    publisher: "Home Office and IOPC",
    url: "https://www.gov.uk/government/publications/home-office-framework-documents/independent-office-for-police-conduct-framework-document-accessible",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "Institutional complaints and conduct oversight remit.",
  },
  {
    id: "hmicfrs-role",
    title: "About HMICFRS",
    publisher: "His Majesty's Inspectorate of Constabulary and Fire & Rescue Services",
    url: "https://hmicfrs.justiceinspectorates.gov.uk/about-us/",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales", "reserved and commissioned inspections"],
    reuse: "link-only",
    personalData: false,
    supports: "Independent inspection and public reporting on police forces and services.",
  },
  {
    id: "cps-role",
    title: "What the Crown Prosecution Service does",
    publisher: "Crown Prosecution Service",
    url: "https://www.cps.gov.uk/about-cps/what-we-do",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "Police investigation, independent prosecution decisions and the courts' separate adjudicative role.",
  },
  {
    id: "cps-accountability",
    title: "How the CPS is kept accountable",
    publisher: "Crown Prosecution Service",
    url: "https://www.cps.gov.uk/about-cps/how-we-are-kept-accountable",
    kind: "official-guidance",
    jurisdictions: ["England", "Wales"],
    reuse: "open",
    personalData: false,
    supports: "DPP accountability and Attorney General superintendence without day-to-day case direction.",
  },
  {
    id: "nca-governance",
    title: "NCA governance and transparency",
    publisher: "National Crime Agency",
    url: "https://www.nationalcrimeagency.gov.uk/who-we-are/governance-and-transparency",
    kind: "official-guidance",
    jurisdictions: ["United Kingdom"],
    reuse: "link-only",
    personalData: false,
    supports: "NCA Director General accountability to the Home Secretary alongside operational independence.",
  },
  {
    id: "scotland-police-act-2012",
    title: "Police and Fire Reform (Scotland) Act 2012",
    publisher: "The National Archives",
    url: "https://www.legislation.gov.uk/asp/2012/8/contents",
    kind: "legislation",
    jurisdictions: ["Scotland"],
    reuse: "open",
    personalData: false,
    supports: "Police Scotland, SPA and Chief Constable functions, control and accountability.",
  },
  {
    id: "spa-governance",
    title: "SPA governance and accountability framework",
    publisher: "Scottish Police Authority",
    url: "https://www.spa.police.uk/publication-library/spa-corporate-governance-framework/annex-a-governance-accountability-framework/",
    kind: "official-guidance",
    jurisdictions: ["Scotland"],
    reuse: "review-required",
    personalData: false,
    supports: "Strategic governance, oversight and accountability relationships for policing in Scotland.",
  },
  {
    id: "pirc-role",
    title: "PIRC: about us",
    publisher: "Police Investigations and Review Commissioner",
    url: "https://www.pirc.scot/help/about-us-faqs",
    kind: "official-guidance",
    jurisdictions: ["Scotland"],
    reuse: "review-required",
    personalData: false,
    supports: "Independent investigation and complaint-review functions in Scotland.",
  },
  {
    id: "copfs-role",
    title: "COPFS role in the justice process",
    publisher: "Crown Office and Procurator Fiscal Service",
    url: "https://www.copfs.gov.uk/about-copfs/our-role-in-the-justice-process/",
    kind: "official-guidance",
    jurisdictions: ["Scotland"],
    reuse: "open",
    personalData: false,
    supports: "Independent prosecution and investigation-of-deaths functions in Scotland.",
  },
  {
    id: "ni-policing-map",
    title: "Policing in Northern Ireland",
    publisher: "Department of Justice Northern Ireland",
    url: "https://www.justice-ni.gov.uk/topics/policing-northern-ireland",
    kind: "official-guidance",
    jurisdictions: ["Northern Ireland"],
    reuse: "review-required",
    personalData: false,
    supports: "PSNI, Northern Ireland Policing Board and independent oversight responsibilities.",
  },
  {
    id: "ppsni-governance",
    title: "PPSNI corporate governance",
    publisher: "Public Prosecution Service for Northern Ireland",
    url: "https://www.ppsni.gov.uk/corporate-governance",
    kind: "official-guidance",
    jurisdictions: ["Northern Ireland"],
    reuse: "review-required",
    personalData: false,
    supports: "PPSNI's independent prosecution governance and accountability.",
  },
  {
    id: "police-recruitment",
    title: "Police careers and volunteering",
    publisher: "police.uk",
    url: "https://www.police.uk/pu/careers-and-volunteering/",
    kind: "official-register",
    jurisdictions: ["England", "Wales"],
    reuse: "link-only",
    personalData: false,
    supports: "Current official recruitment routes; applicant data is never collected.",
  },
  {
    id: "sia-role",
    title: "Security Industry Authority: about us",
    publisher: "Security Industry Authority",
    url: "https://www.gov.uk/government/organisations/security-industry-authority/about",
    kind: "official-guidance",
    jurisdictions: ["United Kingdom, subject to the statutory licensing scope"],
    reuse: "open",
    personalData: false,
    supports: "The SIA's regulation and licensing role for the private security industry.",
  },
  {
    id: "sia-licence-checker",
    title: "Check a private security licence",
    publisher: "Security Industry Authority",
    url: "https://www.gov.uk/check-a-private-security-licence",
    kind: "official-register",
    jurisdictions: ["United Kingdom, subject to the statutory licensing scope"],
    reuse: "link-only",
    personalData: true,
    supports: "Purpose-bound verification of a supplied individual licence; not a bulk personnel directory.",
  },
];

export const integrityScope = {
  schema: "taxsorted.uk.public-integrity-system/1",
  updatedAt: "2026-07-10",
  included: [
    "Typed official-source events for declared interests, benefits, lobbying, contracts, grants, subsidies and corporate land",
    "Law-enforcement institutions, accountability relationships, generic ranks, pay/workforce sources, vacancies and public activities",
    "Named people only for current senior public-accountability offices behind a separate publication gate",
    "Game-like power cards for offices and institutions, with every dimension and legal constraint visible",
  ],
  excluded: [
    "Private addresses, personal contact details, family links and natural-person reverse property searches",
    "Rank-and-file, investigator, intelligence, firearms, protection, shift, deployment or live-incident records",
    "Victim, witness, suspect, conviction, complaint or disciplinary dossiers",
    "Inferred quid pro quo, influence, corruption, guilt, personality, ideology, intent or management style",
  ],
  truthRule:
    "A record says only what its official source establishes. Separate records are not fused into an allegation or causal claim.",
};

export const evidenceEventSchema = {
  schema: "taxsorted.uk.integrity-evidence-event/1",
  eventTypes: [
    "declared_interest",
    "political_donation",
    "political_loan",
    "campaign_spend",
    "ministerial_meeting",
    "gift_hospitality",
    "lobbyist_client_return",
    "appg_benefit",
    "contract_award",
    "grant_award",
    "subsidy_award",
    "corporate_land_title",
    "government_payment",
    "regulatory_outcome",
  ],
  requiredFields: [
    "eventId",
    "eventType",
    "roles",
    "occurrence",
    "sourceObservation",
    "privacy",
    "proves",
    "doesNotProve",
    "causalInference",
  ],
  money:
    "Integer minor units with currency and exact/range/band/estimate basis; never floating-point pounds.",
  joins: {
    allowed: ["exact_official_identifier", "manual_reviewed"],
    candidateOnly: ["name_match"],
    automaticPersonNameJoin: false,
  },
  state: ["source_reported", "official_finding", "corrected", "withdrawn"],
  causalInference: "none",
  exampleNonClaim:
    "This record does not establish influence, a benefit exchange, favouritism, wrongdoing or corruption.",
};

export const financeDatasetCatalog = [
  {
    id: "public-contract-awards",
    title: "Public contract awards",
    endpoint: "/v1/politics/uk/relationships/contracts",
    status: "live",
    publicationClass: "organisation-first",
    safeProjection: ["buyer", "verified organisation supplier", "OCID", "award value", "dates", "classification"],
    excluded: ["addresses", "contact people", "emails", "telephone numbers", "unverified supplier names", "attachment bodies"],
    sourceIds: ["contracts-finder-api"],
  },
  {
    id: "ministerial-gifts-hospitality",
    title: "Ministerial gifts and hospitality",
    endpoint: "/v1/politics/uk/relationships/ministerial-benefits",
    status: "gated-field-and-privacy-review",
    publicationClass: "named-accountability",
    safeProjection: ["minister", "department", "date", "benefit", "direction", "published counterparty", "reported value", "outcome"],
    excluded: ["name-based joins", "private contact details", "inferred benefit exchange"],
    sourceIds: ["ministerial-benefits"],
  },
  {
    id: "commons-financial-interests",
    title: "Commons financial interests",
    endpoint: null,
    status: "mapped-parser-not-built",
    publicationClass: "sensitive-declaration",
    safeProjection: ["member ID", "category", "dates", "corporate organisation", "company number", "declared value", "coarse land description"],
    excluded: ["family categories", "addresses", "residence clues", "natural-person counterparties", "unreviewed free text"],
    sourceIds: ["commons-interests-api"],
  },
  {
    id: "consultant-lobbying",
    title: "Consultant-lobbyist client returns",
    endpoint: null,
    status: "mapped-reuse-and-parser-review",
    publicationClass: "organisation-first",
    safeProjection: ["registrant organisation", "company number", "quarter", "organisation client", "nil return", "code of conduct URL"],
    excluded: ["name-only entity joins", "inferred lobbying outcome"],
    sourceIds: ["consultant-lobbyists-register"],
  },
  {
    id: "ministerial-meetings-travel",
    title: "Ministerial meetings, overseas travel and related transparency returns",
    endpoint: null,
    status: "mapped-parser-and-field-review",
    publicationClass: "named-accountability",
    safeProjection: ["minister", "department", "date or quarter", "organisation counterparty", "published purpose", "reported travel cost"],
    excluded: ["natural-person counterparties without review", "unreviewed free text", "name-only joins", "inferred agreement or influence"],
    sourceIds: ["government-transparency-publications"],
  },
  {
    id: "appg-benefits",
    title: "All-Party Parliamentary Group benefits",
    endpoint: null,
    status: "mapped-reviewed-extraction-not-built",
    publicationClass: "sensitive-declaration",
    safeProjection: ["group", "purpose", "Parliamentary officers", "secretariat organisation", "benefit source", "published value band", "dates"],
    excluded: ["private-person enrichment", "unsupported claim that the group acted for a benefit source"],
    sourceIds: ["appg-register"],
  },
  {
    id: "companies",
    title: "Company identity",
    endpoint: null,
    status: "mapped-identifier-lookup-not-built",
    publicationClass: "organisation-first",
    safeProjection: ["company number", "name", "status", "type", "SIC", "incorporation and filing dates"],
    excluded: ["officer and individual PSC data", "addresses", "birth data", "signatures", "filing images"],
    sourceIds: ["companies-house-api"],
  },
  {
    id: "grants-subsidies",
    title: "Government grants and subsidies",
    endpoint: null,
    status: "mapped-normalisation-not-built",
    publicationClass: "organisation-first",
    safeProjection: ["recipient organisation identifier", "authority", "programme or scheme", "amount or band", "dates", "legal basis"],
    excluded: ["natural-person recipients", "unsupported claims about political involvement"],
    sourceIds: ["government-grants-register", "uk-subsidy-database"],
  },
  {
    id: "department-payments-ipsa-costs",
    title: "Department payments and MPs' business costs",
    endpoint: null,
    status: "mapped-bulk-feed-and-field-review",
    publicationClass: "organisation-first",
    safeProjection: ["public body", "corporate supplier", "amount", "date", "expense type", "contract reference", "MP business-cost category"],
    excluded: ["staff identities or pay", "accommodation detail", "security-sensitive costs", "automated website crawling outside published bulk files"],
    sourceIds: ["government-transparency-publications", "ipsa-publication"],
  },
  {
    id: "charity-identity",
    title: "Charity identity and organisation finances",
    endpoint: null,
    status: "mapped-identifier-lookup-not-built",
    publicationClass: "organisation-first",
    safeProjection: ["charity number", "name", "status", "classifications", "organisation finances", "return dates"],
    excluded: ["trustee and contact-person enrichment", "addresses", "name-only joins"],
    sourceIds: ["charity-commission-api"],
  },
  {
    id: "corporate-land",
    title: "Corporate land ownership in England and Wales",
    endpoint: null,
    status: "blocked-until-dataset-licence-accepted",
    publicationClass: "restricted",
    safeProjection: ["verified company proprietor", "title identifier", "tenure", "broad geography", "proprietor-added date", "reported price"],
    excluded: ["natural-person ownership", "reverse person search", "residential targeting", "property or proprietor addresses until explicitly approved"],
    sourceIds: ["hmlr-public-data", "hmlr-corporate-ownership"],
  },
  {
    id: "electoral-finance",
    title: "Electoral Commission political finance",
    endpoint: "/v1/politics/uk/funding/donations",
    status: "blocked-pending-written-reuse-confirmation",
    publicationClass: "sensitive-declaration",
    safeProjection: ["corporate donor or lender", "company number", "recipient", "amount", "type", "dates"],
    excluded: ["addresses", "postcodes", "sole traders", "individual donors without separate special-category assessment"],
    sourceIds: ["electoral-commission-pfo"],
  },
];

export const enforcementInstitutions = [
  {
    id: "ew-territorial-police",
    name: "Territorial police forces in England and Wales",
    jurisdiction: ["England", "Wales"],
    kind: "police-services",
    role: "Investigate crime, protect the public and exercise policing powers under law through separate territorial forces.",
    officialContact: { label: "Find a police force", url: "https://www.police.uk/pu/contact-the-police/uk-police-forces/" },
    publicDataEndpoint: "/v1/politics/uk/enforcement/forces",
    sourceIds: ["police-api", "chief-constable-profile"],
  },
  {
    id: "ew-pcc-mayors",
    name: "Police and Crime Commissioners and policing mayors",
    jurisdiction: ["England", "Wales"],
    kind: "democratic-policing-accountability",
    role: "Set local police and crime strategy, budget and precept and hold the chief constable to account; they do not command investigations.",
    officialContact: { label: "Local policing governance", url: "https://www.apccs.police.uk/find-your-pcc/" },
    publicDataEndpoint: null,
    sourceIds: ["pcc-panel-guidance"],
  },
  {
    id: "iopc",
    name: "Independent Office for Police Conduct",
    jurisdiction: ["England", "Wales"],
    kind: "police-conduct-oversight",
    role: "Oversees the police complaints system and independently investigates the most serious matters within its remit.",
    officialContact: { label: "IOPC contact routes", url: "https://www.policeconduct.gov.uk/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["iopc-role"],
  },
  {
    id: "hmicfrs",
    name: "HM Inspectorate of Constabulary and Fire & Rescue Services",
    jurisdiction: ["England", "Wales", "commissioned UK work"],
    kind: "inspection",
    role: "Inspects and publicly reports on the efficiency and effectiveness of police forces and specified services.",
    officialContact: { label: "HMICFRS contact", url: "https://hmicfrs.justiceinspectorates.gov.uk/contact-us/" },
    publicDataEndpoint: null,
    sourceIds: ["hmicfrs-role"],
  },
  {
    id: "cps",
    name: "Crown Prosecution Service",
    jurisdiction: ["England", "Wales"],
    kind: "independent-prosecution-service",
    role: "Makes independent charging decisions in serious or complex cases and prosecutes cases following the Code for Crown Prosecutors.",
    officialContact: { label: "CPS contact routes", url: "https://www.cps.gov.uk/contact" },
    publicDataEndpoint: null,
    sourceIds: ["cps-role", "cps-accountability"],
  },
  {
    id: "nca",
    name: "National Crime Agency",
    jurisdiction: ["United Kingdom"],
    kind: "national-law-enforcement-agency",
    role: "Leads and coordinates the UK response to serious and organised crime within its statutory remit.",
    officialContact: { label: "NCA public contact", url: "https://www.nationalcrimeagency.gov.uk/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["nca-governance"],
  },
  {
    id: "police-scotland",
    name: "Police Service of Scotland",
    jurisdiction: ["Scotland"],
    kind: "national-police-service",
    role: "Provides policing across Scotland under the direction and control of the Chief Constable.",
    officialContact: { label: "Police Scotland contact", url: "https://www.scotland.police.uk/contact-us/" },
    publicDataEndpoint: null,
    sourceIds: ["scotland-police-act-2012"],
  },
  {
    id: "spa",
    name: "Scottish Police Authority",
    jurisdiction: ["Scotland"],
    kind: "policing-authority",
    role: "Maintains policing, allocates resources and holds the Chief Constable to account within the Scottish statutory framework.",
    officialContact: { label: "SPA contact", url: "https://www.spa.police.uk/contact-us/" },
    publicDataEndpoint: null,
    sourceIds: ["scotland-police-act-2012", "spa-governance"],
  },
  {
    id: "pirc",
    name: "Police Investigations and Review Commissioner",
    jurisdiction: ["Scotland"],
    kind: "police-investigation-and-complaint-review",
    role: "Conducts independent investigations and complaint handling reviews within its statutory remit.",
    officialContact: { label: "PIRC contact", url: "https://pirc.scot/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["pirc-role"],
  },
  {
    id: "copfs",
    name: "Crown Office and Procurator Fiscal Service",
    jurisdiction: ["Scotland"],
    kind: "independent-prosecution-service",
    role: "Receives reports, directs investigations where legally appropriate and independently decides and conducts prosecutions in Scotland.",
    officialContact: { label: "COPFS contact", url: "https://www.copfs.gov.uk/contact-us/" },
    publicDataEndpoint: null,
    sourceIds: ["copfs-role", "scotland-police-act-2012"],
  },
  {
    id: "psni",
    name: "Police Service of Northern Ireland",
    jurisdiction: ["Northern Ireland"],
    kind: "police-service",
    role: "Provides policing across Northern Ireland under the operational direction of the Chief Constable.",
    officialContact: { label: "PSNI contact", url: "https://www.psni.police.uk/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["ni-policing-map"],
  },
  {
    id: "nipb",
    name: "Northern Ireland Policing Board",
    jurisdiction: ["Northern Ireland"],
    kind: "policing-board",
    role: "Sets the policing plan, appoints senior police leadership through its statutory process and scrutinises PSNI performance without directing operations.",
    officialContact: { label: "Policing Board contact", url: "https://www.nipolicingboard.org.uk/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["ni-policing-map"],
  },
  {
    id: "ppsni",
    name: "Public Prosecution Service for Northern Ireland",
    jurisdiction: ["Northern Ireland"],
    kind: "independent-prosecution-service",
    role: "Independently decides whether to prosecute cases investigated by police or other authorities and conducts prosecutions.",
    officialContact: { label: "PPSNI contact", url: "https://www.ppsni.gov.uk/contact-us" },
    publicDataEndpoint: null,
    sourceIds: ["ppsni-governance"],
  },
  {
    id: "sia",
    name: "Security Industry Authority",
    jurisdiction: ["United Kingdom, subject to statutory scope"],
    kind: "private-security-regulator",
    role: "Regulates specified private-security activities and licenses eligible individuals and approved contractors under its statutory framework.",
    officialContact: { label: "SIA contact", url: "https://www.gov.uk/government/organisations/security-industry-authority" },
    publicDataEndpoint: null,
    sourceIds: ["sia-role", "sia-licence-checker"],
  },
  {
    id: "private-security-sector",
    name: "Licensed private-security providers and workers",
    jurisdiction: ["United Kingdom, subject to statutory scope"],
    kind: "regulated-private-sector",
    role: "Private organisations and licensed workers provide contracted security services; they are not a police service and do not acquire general police powers through employment or an SIA licence.",
    officialContact: { label: "Check an SIA licence", url: "https://www.gov.uk/check-a-private-security-licence" },
    publicDataEndpoint: null,
    sourceIds: ["sia-role", "sia-licence-checker"],
  },
];

export const enforcementRelationships = [
  {
    id: "ew-pcc-strategy",
    type: "sets_strategy_for",
    from: "ew-pcc-mayors",
    to: "ew-territorial-police",
    scope: "Local police and crime plan, budget and precept",
    negativeConstraint: "Does not direct an investigation, arrest, deployment or other operational policing decision.",
    sourceIds: ["pcc-panel-guidance", "chief-constable-profile"],
  },
  {
    id: "ew-chief-operational-command",
    type: "directs_operationally",
    from: "office:ew-chief-constable",
    to: "ew-territorial-police",
    scope: "Direction and control of the force within law and the force area",
    negativeConstraint: "Does not decide whether the CPS prosecutes or whether a court convicts.",
    sourceIds: ["chief-constable-profile", "cps-role"],
  },
  {
    id: "ew-pcc-appoints-chief",
    type: "appoints_and_can_remove",
    from: "ew-pcc-mayors",
    to: "office:ew-chief-constable",
    scope: "Statutory appointment and removal process with police and crime panel scrutiny",
    negativeConstraint: "Appointment accountability does not transfer operational command to the PCC or mayor.",
    sourceIds: ["pcc-panel-guidance"],
  },
  {
    id: "ew-iopc-complaints",
    type: "receives_complaints_about",
    from: "iopc",
    to: "ew-territorial-police",
    scope: "Police complaints system and serious conduct matters within remit",
    negativeConstraint: "A complaint or investigation is not a finding of misconduct.",
    sourceIds: ["iopc-role"],
  },
  {
    id: "ew-hmic-inspection",
    type: "inspects",
    from: "hmicfrs",
    to: "ew-territorial-police",
    scope: "Institutional efficiency and effectiveness inspection",
    negativeConstraint: "Inspection recommendations do not make HMICFRS the operational commander.",
    sourceIds: ["hmicfrs-role"],
  },
  {
    id: "ew-cps-prosecution",
    type: "prosecutes_cases_from",
    from: "cps",
    to: "ew-territorial-police",
    scope: "Cases investigated by police and referred under the charging framework",
    negativeConstraint: "Police investigate; the CPS applies its independent test; courts decide the case.",
    sourceIds: ["cps-role", "cps-accountability"],
  },
  {
    id: "nca-home-secretary-accountability",
    type: "accountable_to",
    from: "nca",
    to: "office:uk-home-secretary",
    scope: "Strategy, governance, funding and Parliamentary accountability",
    negativeConstraint: "The NCA describes its operational decisions as independent; accountability is not case direction.",
    sourceIds: ["nca-governance"],
  },
  {
    id: "scotland-chief-command",
    type: "directs_operationally",
    from: "office:scotland-chief-constable",
    to: "police-scotland",
    scope: "Direction and control of Police Scotland and its resources",
    negativeConstraint: "The Chief Constable remains accountable to the SPA and must comply with lawful prosecutorial instructions in relevant investigations.",
    sourceIds: ["scotland-police-act-2012", "spa-governance"],
  },
  {
    id: "scotland-spa-accountability",
    type: "holds_to_account",
    from: "spa",
    to: "office:scotland-chief-constable",
    scope: "Governance, performance, resource and chief-officer accountability",
    negativeConstraint: "Oversight does not make the SPA the incident commander.",
    sourceIds: ["scotland-police-act-2012", "spa-governance"],
  },
  {
    id: "scotland-copfs-prosecution",
    type: "prosecutes_cases_from",
    from: "copfs",
    to: "police-scotland",
    scope: "Independent prosecution and lawful direction of relevant investigations",
    negativeConstraint: "A police report does not determine the prosecution decision or court outcome.",
    sourceIds: ["copfs-role", "scotland-police-act-2012"],
  },
  {
    id: "ni-board-accountability",
    type: "appoints_and_scrutinises",
    from: "nipb",
    to: "office:psni-chief-constable",
    scope: "Senior appointment, policing plan and performance accountability",
    negativeConstraint: "The Board does not issue operational orders or direct investigations.",
    sourceIds: ["ni-policing-map"],
  },
  {
    id: "ni-chief-command",
    type: "directs_operationally",
    from: "office:psni-chief-constable",
    to: "psni",
    scope: "Direction and control of PSNI operations",
    negativeConstraint: "Operational command does not decide independent PPSNI prosecutions or court outcomes.",
    sourceIds: ["ni-policing-map", "ppsni-governance"],
  },
  {
    id: "ni-pps-prosecution",
    type: "prosecutes_cases_from",
    from: "ppsni",
    to: "psni",
    scope: "Independent prosecution decisions on referred investigations",
    negativeConstraint: "Referral, charge and conviction are separate states.",
    sourceIds: ["ppsni-governance", "ni-policing-map"],
  },
  {
    id: "sia-private-security-regulation",
    type: "regulates_and_licenses",
    from: "sia",
    to: "private-security-sector",
    scope: "Licensable private-security activities and the approved-contractor scheme within statute",
    negativeConstraint: "An SIA licence or private employment does not confer the office of constable or general police powers, and the individual checker is not a bulk directory.",
    sourceIds: ["sia-role", "sia-licence-checker"],
  },
];

export const enforcementTransparencyCollections = {
  ranksAndRoles: {
    status: "source-linked-generic-roles",
    rule: "Ranks describe generic responsibility, not a named-person roster or a live incident command chain.",
    families: [
      { jurisdiction: "England and Wales", order: ["Constable", "Sergeant", "Inspector", "Chief Inspector", "Superintendent", "Chief Superintendent", "Assistant Chief Constable", "Deputy Chief Constable", "Chief Constable"], sourceIds: ["chief-constable-profile"] },
      { jurisdiction: "Scotland", order: ["Constable", "Sergeant", "Inspector", "Chief Inspector", "Superintendent", "Chief Superintendent", "Assistant Chief Constable", "Deputy Chief Constable", "Chief Constable"], sourceIds: ["scotland-police-act-2012"] },
      { jurisdiction: "Northern Ireland", order: ["Constable", "Sergeant", "Inspector", "Chief Inspector", "Superintendent", "Chief Superintendent", "Assistant Chief Constable", "Deputy Chief Constable", "Chief Constable"], sourceIds: ["ni-policing-map"] },
    ],
  },
  payAndBenefits: {
    status: "england-wales-current-ranges-normalised-other-jurisdictions-source-linked",
    rule: "Version every band by jurisdiction, rank, pay point and effective date. Keep base pay, allowances, pension and senior remuneration separate.",
    currentEnglandWales: {
      asAt: "2026-07-10",
      effectiveFrom: "2025-09-01",
      amountUnit: "GBP minor units per year",
      scope: "Base salary ranges published in the Home Office's 2026 to 2027 evidence; London and other allowances are separate.",
      rankRanges: [
        { rank: "Constable", minimumMinor: 3_116_400, maximumMinor: 5_025_600 },
        { rank: "Sergeant", minimumMinor: 5_356_800, maximumMinor: 5_620_800 },
        { rank: "Inspector", minimumMinor: 6_376_800, maximumMinor: 6_898_200 },
        { rank: "Chief Inspector", minimumMinor: 7_034_400, maximumMinor: 7_314_900 },
        { rank: "Superintendent", minimumMinor: 8_417_700, maximumMinor: 9_901_500 },
        { rank: "Chief Superintendent", minimumMinor: 10_379_700, maximumMinor: 11_578_500 },
      ],
      benefits: [
        { kind: "defined-benefit-pension", detail: "Inflation-linked pension based on salary and service; employer contribution stated as 35.3%." },
        { kind: "pay-progression", detail: "Subject to the pay progression standard, a constable typically reaches the top in six years and other ranks in three to four years." },
        { kind: "unsocial-hours", detail: "Federated ranks receive 10% of basic hourly pay for eligible hours worked between 20:00 and 06:00." },
        { kind: "other-allowances", detail: "Away-from-home, on-call, hardship, location and other allowances have separate eligibility rules and must not be folded into base pay." },
      ],
      sourceIds: ["police-pay-ew-2026"],
    },
    datasets: [
      { jurisdiction: "England and Wales", coverage: "Rank pay scales, allowances, pensions and remuneration evidence", sourceIds: ["police-pay-ew-2026"] },
      { jurisdiction: "Scotland", coverage: "Police Scotland rewards and benefits", url: "https://www.scotland.police.uk/jobs/police-officer/rewards-and-benefits/", sourceIds: [] },
      { jurisdiction: "Northern Ireland", coverage: "PSNI official recruitment terms and benefits", url: "https://www.joinpsni.co.uk/police-officer", sourceIds: [] },
    ],
  },
  workforce: {
    status: "aggregate-only",
    rule: "Preserve official suppression. Do not expose individual characteristics or permit small-cell differencing.",
    datasets: [
      { id: "police-workforce-england-wales", jurisdiction: "England and Wales", coverage: "Force, rank, FTE, sex and ethnicity aggregate tables", sourceIds: ["police-workforce-ew"] },
      { id: "police-officer-strength-scotland", jurisdiction: "Scotland", coverage: "Quarterly police officer strength", url: "https://www.gov.scot/collections/police-officer-quarterly-strength-statistics-scotland/", sourceIds: [] },
      { id: "psni-workforce", jurisdiction: "Northern Ireland", coverage: "PSNI workforce composition and strength", url: "https://www.psni.police.uk/about-us/our-publications-and-reports/our-publication-scheme/who-we-are-and-what-we-do/workforce", sourceIds: [] },
    ],
  },
  funding: {
    status: "official-sources-mapped-values-not-normalised",
    rule: "Keep central grant, local precept, capital, reserves, budget requirement and actual expenditure as separate measures.",
    datasets: [{ id: "police-grants-england-wales-2026-27", jurisdiction: "England and Wales", coverage: "2026 to 2027 police grant allocations", sourceIds: ["police-grants-ew-2026"] }],
  },
  vacancies: {
    status: "official-links-only",
    rule: "Return only current role title, closing date and official application link. Never collect applicant data.",
    routes: [
      { id: "police-careers-england-wales", label: "Police careers in England and Wales", url: "https://www.police.uk/pu/careers-and-volunteering/" },
      { id: "police-scotland-recruitment", label: "Police Scotland recruitment", url: "https://www.scotland.police.uk/recruitment/" },
      { id: "psni-recruitment", label: "PSNI recruitment", url: "https://www.joinpsni.co.uk/" },
      { id: "nca-careers", label: "National Crime Agency careers", url: "https://www.nationalcrimeagency.gov.uk/careers" },
      { id: "civil-service-jobs", label: "Civil Service Jobs", url: "https://www.civilservicejobs.service.gov.uk/" },
    ],
  },
  publicActivities: {
    status: "institutional-only",
    included: ["Published board meetings", "Agendas and minutes", "Inspection programmes and reports", "Annual reports", "Strategies", "Official speeches"],
    excluded: ["Live or future deployments", "Tactical plans", "Response routes", "Control rooms", "Protected sites", "Named officer activity logs"],
  },
  privateSecurity: {
    status: "institution-and-company-first-individual-checker-link-only",
    included: ["SIA institutional remit", "Official SIA contact", "Verified company identity", "Public contract awards to verified companies", "Official one-record licence-check route"],
    excluded: ["Bulk individual licence-holder directory", "Worker home or duty location", "Shift or client-site roster", "Inferred police power", "Private contact enrichment"],
    sourceIds: ["sia-role", "sia-licence-checker", "companies-house-api", "contracts-finder-api"],
  },
};

const enforcementPowerDimensions = [
  { id: "coercive", label: "Coercive authority", meaning: "Use or authorise police, detention, search or compulsory legal powers." },
  { id: "operational", label: "Operational direction", meaning: "Direct an institution's operational work; policy sponsorship alone scores zero." },
  { id: "prosecution", label: "Prosecution discretion", meaning: "Make independent charging or prosecution decisions." },
  { id: "rulesSanctions", label: "Rules and sanctions", meaning: "Make binding rules, decide disciplinary/regulatory outcomes or impose sanctions." },
  { id: "resources", label: "Money and resources", meaning: "Set, approve or control budgets and organisational resources." },
  { id: "appointments", label: "Appointments and removal", meaning: "Appoint, dismiss or formally nominate senior public leadership." },
  { id: "scope", label: "Geographic scope", meaning: "Formal territorial reach; this is displayed separately and is not fame or influence." },
] as const;

type EnforcementPowerDimension = (typeof enforcementPowerDimensions)[number]["id"];
type EnforcementPowerScore = 0 | 1 | 2 | 3 | 4 | 5;

function enforcementPowerCard(input: {
  officeId: string;
  officeName: string;
  officeFamily: string;
  jurisdiction: string[];
  exerciseMode: string;
  scores: Record<EnforcementPowerDimension, EnforcementPowerScore>;
  constraints: string[];
  sourceIds: string[];
}) {
  const raw = Object.values(input.scores).reduce<number>((total, score) => total + score, 0);
  return {
    ...input,
    methodVersion: "taxsorted.uk.enforcement-office-power/1.0.0-draft",
    calculation: { raw, maximum: 35, display: Math.round((raw / 35) * 20) * 5 },
    warning: "This rates the office's formal authority, not its holder's character, performance, relationships or integrity.",
    researchDepth: Object.entries(input.scores)
      .filter(([, score]) => score >= 3)
      .map(([dimension]) => dimension),
    evidenceCoverage: "partial",
    lawAsAt: "2026-07-10",
  };
}

export const enforcementPowerMethod = {
  schema: "taxsorted.uk.enforcement-office-power/1",
  version: "1.0.0-draft",
  dimensions: enforcementPowerDimensions,
  rubric: [
    { score: 0, meaning: "Reviewed: no authority identified in this dimension." },
    { score: 1, meaning: "Advisory, procedural or exceptionally narrow authority." },
    { score: 2, meaning: "Bounded authority, delegated function or one vote in a collective body." },
    { score: 3, meaning: "Material authority in a defined domain with strong checks or co-decision." },
    { score: 4, meaning: "Primary authority across a substantial institution or portfolio." },
    { score: 5, meaning: "Primary formal authority across most of the dimension in scope; never above the law." },
  ],
  comparison:
    "No global leaderboard. Compare only offices in the same family, jurisdiction and method version; always show all seven dimensions.",
};

export const enforcementPowerCards = [
  enforcementPowerCard({
    officeId: "ew:office:chief-constable",
    officeName: "Territorial Chief Constable baseline",
    officeFamily: "England and Wales territorial policing",
    jurisdiction: ["One territorial force area"],
    exerciseMode: "operationally-independent",
    scores: { coercive: 5, operational: 5, prosecution: 0, rulesSanctions: 2, resources: 4, appointments: 3, scope: 3 },
    constraints: ["PCC or mayor sets strategy and budget but cannot command operations.", "CPS makes independent prosecution decisions; courts adjudicate.", "Police powers, human rights, inspection, complaints and judicial review constrain the office."],
    sourceIds: ["chief-constable-profile", "pcc-panel-guidance", "cps-role", "iopc-role", "hmicfrs-role"],
  }),
  enforcementPowerCard({
    officeId: "ew:office:pcc-mayor-baseline",
    officeName: "Police and Crime Commissioner / policing mayor baseline",
    officeFamily: "England and Wales democratic policing accountability",
    jurisdiction: ["One police area"],
    exerciseMode: "individual-with-panel-scrutiny",
    scores: { coercive: 0, operational: 0, prosecution: 0, rulesSanctions: 2, resources: 4, appointments: 5, scope: 3 },
    constraints: ["Cannot direct investigations, arrests, deployments or incident command.", "Police and crime panel scrutinises core decisions.", "The chief constable retains operational direction and control."],
    sourceIds: ["pcc-panel-guidance", "chief-constable-profile"],
  }),
  enforcementPowerCard({
    officeId: "uk:office:home-secretary-law-enforcement-baseline",
    officeName: "Home Secretary law-enforcement baseline",
    officeFamily: "UK government sponsorship and policing policy",
    jurisdiction: ["United Kingdom with functions varying by devolution and statute"],
    exerciseMode: "ministerial-and-statutory",
    scores: { coercive: 1, operational: 0, prosecution: 0, rulesSanctions: 4, resources: 4, appointments: 3, scope: 5 },
    constraints: ["Political accountability and funding do not create a power to order an individual investigation or prosecution.", "Devolved policing systems have separate ministers and institutions.", "Portfolio-specific powers must be sourced individually before use."],
    sourceIds: ["police-grants-ew-2026", "nca-governance", "chief-constable-profile", "cps-accountability"],
  }),
  enforcementPowerCard({
    officeId: "ew:office:director-of-public-prosecutions",
    officeName: "Director of Public Prosecutions",
    officeFamily: "England and Wales prosecution",
    jurisdiction: ["England", "Wales"],
    exerciseMode: "independent-prosecutorial",
    scores: { coercive: 1, operational: 4, prosecution: 5, rulesSanctions: 3, resources: 3, appointments: 3, scope: 4 },
    constraints: ["Police investigate; courts decide guilt and sentence.", "Attorney General superintendence is not day-to-day direction of individual cases.", "The Code for Crown Prosecutors and public law constrain prosecution decisions."],
    sourceIds: ["cps-role", "cps-accountability"],
  }),
  enforcementPowerCard({
    officeId: "uk:office:nca-director-general",
    officeName: "NCA Director General",
    officeFamily: "UK national law enforcement",
    jurisdiction: ["United Kingdom, with jurisdiction-specific arrangements"],
    exerciseMode: "operationally-independent",
    scores: { coercive: 5, operational: 5, prosecution: 0, rulesSanctions: 2, resources: 4, appointments: 4, scope: 5 },
    constraints: ["Prosecution authorities make independent prosecution decisions.", "Accountable to the Home Secretary and Parliament while operational decisions remain independent.", "Statutory powers and territorial arrangements define reach."],
    sourceIds: ["nca-governance", "cps-role", "ppsni-governance", "copfs-role"],
  }),
  enforcementPowerCard({
    officeId: "scotland:office:chief-constable",
    officeName: "Chief Constable of the Police Service of Scotland",
    officeFamily: "Scottish policing",
    jurisdiction: ["Scotland"],
    exerciseMode: "operationally-independent",
    scores: { coercive: 5, operational: 5, prosecution: 0, rulesSanctions: 2, resources: 4, appointments: 3, scope: 5 },
    constraints: ["SPA provides governance and holds the office to account.", "COPFS and the Lord Advocate exercise independent prosecution functions and may give lawful instructions in relevant investigations.", "PIRC and HMICS provide separate oversight routes."],
    sourceIds: ["scotland-police-act-2012", "spa-governance", "copfs-role", "pirc-role"],
  }),
  enforcementPowerCard({
    officeId: "ni:office:psni-chief-constable",
    officeName: "PSNI Chief Constable",
    officeFamily: "Northern Ireland policing",
    jurisdiction: ["Northern Ireland"],
    exerciseMode: "operationally-independent",
    scores: { coercive: 5, operational: 5, prosecution: 0, rulesSanctions: 2, resources: 4, appointments: 3, scope: 5 },
    constraints: ["Northern Ireland Policing Board appoints and scrutinises but does not direct operations.", "PPSNI independently decides prosecutions.", "Police Ombudsman and inspection bodies have separate oversight roles."],
    sourceIds: ["ni-policing-map", "ppsni-governance"],
  }),
];

export const observableOfficialLanguageMethod = {
  schema: "taxsorted.uk.observable-official-language/1",
  status: "method-only-identifiable-analysis-blocked-pending-lia-dpia",
  name: "Observable language in official texts",
  purpose:
    "Describe reproducible surface features of an attributable public corpus. It is not a personality, honesty, aggression, manipulation, ideology, competence, emotion, management-style or intent assessment.",
  allowedCorpora: [
    "Hansard contributions",
    "Official speeches clearly attributed as delivered by the office-holder",
    "Signed official letters",
    "Official interview transcripts published by the institution",
  ],
  authorshipRule:
    "A department press release belongs to the institution unless the source explicitly establishes personal authorship. Delivered by does not mean written by.",
  minimumCorpus: { documents: 10, words: 5_000, dates: 3, spanDays: 30 },
  deterministicMetrics: [
    "Median words per sentence",
    "Question sentences per 1,000 sentences",
    "First-person singular and plural pronouns per 1,000 words",
    "Obligation and possibility modal terms per 1,000 words",
    "Contrast connectors per 1,000 words",
    "Numeric-token rate",
    "Median speaking-turn length",
    "Repeated-phrase rate without republishing phrases",
  ],
  requiredOutput: ["numerator", "denominator", "tokeniser version", "language", "corpus dates", "source URLs", "content hashes"],
  prohibited: ["personality label", "psychographic profile", "sentiment score", "rhetorical manipulation score", "person ranking", "employment or enforcement use"],
};

export const integrityCorrectionMethod = {
  schema: "taxsorted.uk.public-integrity-corrections/1",
  status: "process-defined-public-intake-not-yet-live",
  reasonNamedGatesRemainClosed:
    "Named source families must not open until a working private correction, objection and urgent-safety route is published and tested.",
  correctionKinds: [
    {
      id: "official-source-error",
      meaning: "The upstream public body or register appears to be wrong.",
      handling: "Link the person to the publisher's correction route and restrict TaxSorted processing when accuracy or safety is plausibly disputed.",
    },
    {
      id: "taxsorted-mapping-error",
      meaning: "TaxSorted copied, filtered, joined, dated or described the official record incorrectly.",
      handling: "Restrict the affected record, reproduce the mapping, correct it, purge caches and publish a dated correction or tombstone.",
    },
    {
      id: "privacy-objection",
      meaning: "A person objects to or asks to restrict TaxSorted's processing.",
      handling: "Open a private case, record the applicable right and lawful-basis review, and never publish the requester's evidence or identity.",
    },
    {
      id: "urgent-identity-address-safety",
      meaning: "The record may identify the wrong person, reveal a private location or create a credible safety risk.",
      handling: "Immediately restrict the field or record while checking it; do not wait for the ordinary editorial queue.",
    },
  ],
  safeRequestFields: ["TaxSorted record URL", "official source URL", "field or statement disputed", "plain explanation", "preferred private reply route"],
  neverSubmitPublicly: ["identity documents", "home address", "police report", "medical information", "family details", "unredacted private correspondence"],
  publicChangeRecord: ["dataset revision", "record ID", "changed at", "change kind", "supersedes", "tombstone state", "neutral explanation"],
  operationalRequirements: ["private intake", "access control", "proportionate identity verification", "restriction flag", "cache purge", "downstream notification", "reviewed re-enablement"],
};
